### ISSUE TITLE
Include Android Support

### ISSUE THREAD

**Issue by rturk** [cardash/react-native-openalpr#2] opened 2017-03-02 09:39 UTC

**Comment by kevinjpetersen** [comment] 2017-03-05 02:44
+1

**Comment by emrosenf** [comment] 2017-03-06 17:59
Can anyone help with this? Get in touch with me or @samcorcos

**Comment by jonathanpalma** [comment] 2017-06-14 23:46
@emrosenf I would be glad to help with this. Actually I'm supporting a [tesseract-ocr wrapper for react native](https://github.com/jonathanpalma/react-native-tesseract-ocr). But for now it is only working on android. It would be nice if somebody of this project's collaborators could help me with the iOS implementation in exchange for giving android support to this project.

**Comment by jreason** [comment] 2017-08-01 11:34
Hi Guys, any progress with this?

**Comment by emrosenf** [comment] 2017-08-02 20:13
@jreason @jonathanpalma @kevinjpetersen @rturk There is a new pull request for Android. Would you be willing to test it?

**Comment by jreason** [comment] 2017-08-03 14:32
@emrosenf great news! It might be a week or two before i get onto it but most definately!

**Comment by baozdemir** [comment] 2017-08-08 22:10
+1

**Comment by samcorcos** [comment] 2017-08-08 22:59
@baozdemir As it happens, there is an active pull request. Would you mind testing it? We don't have the bandwidth right now.

**Comment by baozdemir** [comment] 2017-08-09 07:55
@samcorcos  I can do end-user testing. I may not have enough technical knowledge in React native.

**Comment by samcorcos** [comment] 2017-08-09 15:47
@baozdemir That would be great! Thank you.

**Comment by baozdemir** [comment] 2017-08-12 01:27
![error](https://user-images.githubusercontent.com/9097009/29235892-22508534-7f0c-11e7-928b-4794e7c99c52.png)

I think I have completely implemented all the steps in doc. but I get this error. If the problem is from me please warn me. Thanks.

**Comment by emrosenf** [comment] 2017-08-21 18:35
Android support has been merged!

**Closed by emrosenf** 2017-08-21 18:35 UTC
