### ISSUE TITLE
Pull Request for Include Android Support

### ISSUE THREAD

**Issue by baozdemir** [cardash/react-native-openalpr#12] opened 2017-08-14 11:24 UTC
![error](https://user-images.githubusercontent.com/9097009/29235892-22508534-7f0c-11e7-928b-4794e7c99c52.png)
I am trying to test [this](https://github.com/cardash/react-native-openalpr/pull/11) pull request.
I have completely implemented all the steps in [doc](https://github.com/cardash/react-native-openalpr/tree/22722856d8b46be99c38b588a81b458a96f82643) pull request and I get this error on step 4.
@JohnYangSam

**Comment by Progoogler** [comment] 2017-08-19 20:10
It seems that appending the `/libraries` path to the project's settings.gradle as such:
```
':react-native-openalpr'
project(':react-native-openalpr').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-openalpr/android/libraries')
```
fixes the routing issue. However, it's encountering another error:
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.
```
After looking around, the consensus around such an error is that the gradle files are encountering errors while building, so `getConfiguration()` returns `default`. This leads me to believe that the cause of the error lies somewhere in either of the three `build.gradle` files in the android, opencv, or openalpr directories.
@baozdemir

**Comment by Progoogler** [comment] 2017-08-19 21:22
This may be a false notion.. but what I did was I deleted both
```
compile project('openalpr')
compile project('opencv')
```
from the the react-native-openalpr android/build.gradle and added them to my project's android/build.gradle so that the dependencies look like:
```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-openalpr')
    compile project(':openalpr')
    compile project(':opencv')
}
```
Then I noticed in settings.gradle that there was a typo in the new Android Installation doc
```
include ':open-alpr'
project(':open-alpr').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-openalpr/android/libraries/open-alpr')
```
should be (w/o the ' - '):
```
include ':openalpr'
project(':openalpr').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-openalpr/android/libraries/openalpr')
```
Now when I run `./gradlew installDebug` it's able to configure 5/5 of the projects and build up to 60% before failing with the following error:
```
14:16:09.279 [ERROR] [org.gradle.api.Project] /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/src/main/res/layout/camera_layout.xml:7: AAPT: No resource identifier found for attribute 'camera_id' in package 'com.cardash.openalpr'
    
14:16:09.280 [ERROR] [org.gradle.api.Project] /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/src/main/res/layout/camera_layout.xml:7: AAPT: No resource identifier found for attribute 'show_fps' in package 'com.cardash.openalpr'
    
14:16:09.280 [ERROR] [org.gradle.api.Project] /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/res/merged/release/layout/camera_layout.xml:7: error: No resource identifier found for attribute 'camera_id' in package 'com.cardash.openalpr'

/home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/res/merged/release/layout/camera_layout.xml:7: error: No resource identifier found for attribute 'show_fps' in package 'com.cardash.openalpr'


14:16:09.282 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':react-native-openalpr:processReleaseResources'
14:16:09.282 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :react-native-openalpr:processReleaseResources FAILED
14:16:09.282 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :react-native-openalpr:processReleaseResources (Thread[main,5,main]) completed. Took 0.264 secs.
14:16:09.282 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 1.208 secs, idle: 0.015 secs
14:16:09.288 [ERROR] [org.gradle.BuildExceptionReporter] 
14:16:09.290 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:16:09.290 [ERROR] [org.gradle.BuildExceptionReporter] 
14:16:09.290 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:16:09.290 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':react-native-openalpr:processReleaseResources'.
14:16:09.290 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.ide.common.process.ProcessException: Failed to execute aapt
14:16:09.291 [ERROR] [org.gradle.BuildExceptionReporter] 
14:16:09.291 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-openalpr:processReleaseResources'.
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
14:16:09.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
14:16:09.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
14:16:09.294 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
14:16:09.295 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Failed to execute aapt
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:185)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:82)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
14:16:09.296 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter]        ... 60 more
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: com.android.ide.common.process.ProcessException: Failed to execute aapt
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:873)
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:178)
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter]        ... 68 more
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing '/home/azali/Android/Sdk/build-tools/25.0.0/aapt' with arguments {package -f --no-crunch -I /home/azali/Android/Sdk/platforms/android-23/android.jar -M /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/manifests/aapt/release/AndroidManifest.xml -S /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/res/merged/release -m -J /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/generated/source/r/release --custom-package com.cardash.openalpr --non-constant-id -0 apk --output-text-symbols /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/bundles/release --no-version-vectors}
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
14:16:09.297 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:871)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        ... 69 more
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: com.android.ide.common.process.ProcessException: Error while executing '/home/azali/Android/Sdk/build-tools/25.0.0/aapt' with arguments {package -f --no-crunch -I /home/azali/Android/Sdk/platforms/android-23/android.jar -M /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/manifests/aapt/release/AndroidManifest.xml -S /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/res/merged/release -m -J /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/generated/source/r/release --custom-package com.cardash.openalpr --non-constant-id -0 apk --output-text-symbols /home/azali/brogramming/machine-learning/alpr_test_app/node_modules/react-native-openalpr/android/build/intermediates/bundles/release --no-version-vectors}
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:75)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:78)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:74)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
14:16:09.298 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.process.GradleProcessExecutor$1.run(GradleProcessExecutor.java:60)
14:16:09.299 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/azali/Android/Sdk/build-tools/25.0.0/aapt'' finished with non-zero exit value 1
14:16:09.299 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
14:16:09.299 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:47)
14:16:09.299 [ERROR] [org.gradle.BuildExceptionReporter]        ... 9 more
14:16:09.299 [ERROR] [org.gradle.BuildExceptionReporter] 
14:16:09.299 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:16:09.299 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:16:09.299 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:16:09.299 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 11.822 secs

```

Any thoughts on how we can fix this referencing issue in `camera_layout.xml`? @baozdemir @JohnYangSam

**Comment by Progoogler** [comment] 2017-08-19 22:26
Ok, so that whole removing the
```
compile project('openalpr')
compile project('opencv')
```
from react-native-openalpr/android/build.gradle turned out to be a false notion after all.
I added that back without removing anything from the project's android/build.gradle and that allowed for the resource identifier to be found within compiled packages of the library's build.gradle.
The only other change I had to make was set minSdkVersion of the project's build.gradle
```
defaultConfig {
    minSdkVersion 16
}
```
to `minSdkVersion 21` because it couldn't be lower than that of the library's. This allowed the project to build successfully. I'll be back later to update on how the test phase goes.

**Comment by baozdemir** [comment] 2017-08-19 22:30
@Progoogler  Thanks for be interested. I will continue testing as soon as possible.

**Comment by JohnYangSam** [comment] 2017-08-20 00:06
@Progoogler to clarify - so with the updated minSdkVersion you were able to have it working on your end? We can update the pull request if so, otherwise, we'll dig on our end and try to reproduce your error.

**Comment by Progoogler** [comment] 2017-08-20 18:48
It's working!
![screenshot_2017-08-20-10-12-38](https://user-images.githubusercontent.com/16564838/29497392-b1b9db4a-859b-11e7-8fe1-0ae996d6d371.png)
@JohnYangSam The minSdkVersion was one of the hurdles. On my second attempt, instead of changing my project's minSdkVersion to match the library's `21`, I changed the library's to `16` and it still worked. This approach seems preferable. - Would you authorize me as a contributor to your PR so that I may merge that and the other changes?

In the meantime, I'm looking into configuring the `react-native link` process so that it includes those manual changes.

@baozdemir Happy to be onboard! :D

**Comment by emrosenf** [comment] 2017-08-20 20:49
@Progoogler I've added you as a collaborator to this repo so you can contribute your fix

**Comment by JohnYangSam** [comment] 2017-08-21 16:52
updates made related to the minSdkVersion here: https://github.com/cardash/react-native-openalpr/pull/11#issuecomment-323796385

**Comment by emrosenf** [comment] 2017-08-21 18:35
PR merged, closing

**Closed by emrosenf** 2017-08-21 18:35 UTC
